const cssVar = <Name extends `--ka-v2-${string}`>(name: Name) => `var(${name})` as const;

export const tokens = {
  color: {
    canvas: cssVar("--ka-v2-color-canvas"),
    surface: cssVar("--ka-v2-color-surface"),
    surfaceMuted: cssVar("--ka-v2-color-surface-muted"),
    inverse: cssVar("--ka-v2-color-inverse"),
    text: cssVar("--ka-v2-color-text"),
    textMuted: cssVar("--ka-v2-color-text-muted"),
    textOnInverse: cssVar("--ka-v2-color-text-on-inverse"),
    border: cssVar("--ka-v2-color-border"),
    borderStrong: cssVar("--ka-v2-color-border-strong"),
    accent: cssVar("--ka-v2-color-accent"),
    accentHover: cssVar("--ka-v2-color-accent-hover"),
    accentSoft: cssVar("--ka-v2-color-accent-soft"),
    success: cssVar("--ka-v2-color-success"),
    successSoft: cssVar("--ka-v2-color-success-soft"),
    warning: cssVar("--ka-v2-color-warning"),
    warningSoft: cssVar("--ka-v2-color-warning-soft"),
    danger: cssVar("--ka-v2-color-danger"),
    dangerSoft: cssVar("--ka-v2-color-danger-soft"),
    focus: cssVar("--ka-v2-color-focus"),
    overlay: cssVar("--ka-v2-color-overlay"),
  },
  space: {
    0: cssVar("--ka-v2-space-0"),
    1: cssVar("--ka-v2-space-1"),
    2: cssVar("--ka-v2-space-2"),
    3: cssVar("--ka-v2-space-3"),
    4: cssVar("--ka-v2-space-4"),
    5: cssVar("--ka-v2-space-5"),
    6: cssVar("--ka-v2-space-6"),
    8: cssVar("--ka-v2-space-8"),
    10: cssVar("--ka-v2-space-10"),
    12: cssVar("--ka-v2-space-12"),
    16: cssVar("--ka-v2-space-16"),
    20: cssVar("--ka-v2-space-20"),
    24: cssVar("--ka-v2-space-24"),
  },
  radius: {
    none: cssVar("--ka-v2-radius-none"),
    sm: cssVar("--ka-v2-radius-sm"),
    md: cssVar("--ka-v2-radius-md"),
    lg: cssVar("--ka-v2-radius-lg"),
    pill: cssVar("--ka-v2-radius-pill"),
  },
  shadow: {
    none: cssVar("--ka-v2-shadow-none"),
    soft: cssVar("--ka-v2-shadow-soft"),
    raised: cssVar("--ka-v2-shadow-raised"),
    overlay: cssVar("--ka-v2-shadow-overlay"),
  },
  motion: {
    fast: cssVar("--ka-v2-motion-fast"),
    standard: cssVar("--ka-v2-motion-standard"),
    slow: cssVar("--ka-v2-motion-slow"),
    easing: cssVar("--ka-v2-motion-easing"),
  },
  layout: {
    content: cssVar("--ka-v2-layout-content"),
    reading: cssVar("--ka-v2-layout-reading"),
    gutter: cssVar("--ka-v2-layout-gutter"),
    section: cssVar("--ka-v2-layout-section"),
    control: cssVar("--ka-v2-control-height"),
    controlLarge: cssVar("--ka-v2-control-height-lg"),
    target: cssVar("--ka-v2-target-size"),
  },
} as const;

export type DesignTokenMap = typeof tokens;
